apps/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.lista_usuario, name='lista_usuario'),
    path('<int:id>', views.ver_usuario, name='ver_usuario'),
    path('agregar', views.agregar_usuario, name='agregar_usuario'),
    path('eliminar/<int:id>', views.eliminar_usuario, name='eliminar_usuario'),
    path('modificar/<int:id>', views.modificar_usuario, name='modificar_usuario'),
    path('cambiar/<int:id>', views.cambiar_contrasena, name='cambiar_contrasena'),
]

scatuaz/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trabajador/', include('apps.trabajador.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('', include('apps.login.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/trabajador/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from apps.usuario.models import UserSCATUAZ

OPCIONES_SEXO = (
    ('0', 'Masculino'),
    ('1', 'Femenino'),
)

OPCIONES_ESTUDIOS = (
    ('0', 'Primaria'),
    ('1', 'Secundaria'),
    ('2', 'Bachillerato o Preparatoria'),
    ('3', 'Carrera Comercial'),
    ('4', 'Carrera Técnica'),
    ('5', 'Normal'),
    ('6', 'Normal Superior'),
    ('7', 'Licenciatura'),
    ('8', 'Pasante de Carrera Profesional'),
    ('9', 'Especialidad'),
    ('10', 'Maestría'),
    ('11', 'Doctorado'),
    ('12', 'Pasante de Maestría'),
    ('13', 'Candidato a Doctor'),
    ('14', 'Postdoctorado'),
)

OPCIONES_BOOL = (
    ('0', 'No'),
    ('1', 'Si'),
)

def get_docs_path(instance, filename):
    return f'docs/trabajador/{instance.id_trabajador.rfc}/{filename}'

def get_docs_path_2(instance, filename):
    return f'docs/trabajador/{instance.id_doc_academicos.id_trabajador.rfc}/{filename}'

class Trabajador(models.Model):
    nombre = models.CharField('*Nombre(s)', max_length=100)
    paterno = models.CharField('*Primer apellido', max_length=100)
    materno = models.CharField('*Segundo apellido', max_length=100)
    rfc = models.CharField('*RFC', max_length=13, unique=True)
    curp = models.CharField('*CURP', max_length=18, unique=True)
    sexo = models.CharField('*Genero', max_length=1, choices=OPCIONES_SEXO)
    pais_residencia = models.CharField('*Pais de residencia', max_length=100)
    estado_residencia = models.CharField('*Estado de residencia', max_length=100)
    municipio_residencia = models.CharField('*Municipio de residencia', max_length=100)
    calle = models.CharField('*Calle', max_length=100)
    numero = models.CharField('*Numero', max_length=10)
    colonia = models.CharField('*Colonia', max_length=100)
    cp = models.CharField('*CP', max_length=6)
    telefono = models.CharField('*Telefono', max_length=10, unique=True)
    email = models.CharField('*Correo electronico', max_length=50, unique=True)
    matricula_administrativo = models.CharField('*Matricula administrativa', max_length=6, unique=True)
    matricula_gremial = models.CharField('*Matricula gremial', max_length=6, unique=True)
    grado_max_estudios = models.CharField('*Grado maximo de estudios', max_length=2, choices=OPCIONES_ESTUDIOS)
    nss = models.CharField('*Numero de seguro social (NSS)', max_length=11, unique=True)
    no_issste = models.CharField('*Numero de ISSSTE', max_length=50, unique=True)
    validado_renapo = models.CharField('Validado por Renapo', max_length=1, null=True, choices=OPCIONES_BOOL)
    validado_siri = models.CharField('Validado por Siri', max_length=1, null=True, choices=OPCIONES_BOOL)
    alta_usuario = models.ForeignKey(UserSCATUAZ, verbose_name="Usuario", null=True, on_delete=models.SET_NULL)
    alta_fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return (self.nombre + ' ' + self.paterno + ' ' + self.materno).strip()


class Actualizacion(models.Model):
    id_trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    usuario = models.ForeignKey(UserSCATUAZ, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    comentario = models.TextField('Comentario', max_length=500, null=True)
    

################ Documentos personales ################
class DocumentosPersonales(models.Model):
    id_trabajador = models.OneToOneField(Trabajador, on_delete=models.CASCADE, unique=True)
    acta_nacimiento = models.FileField('Acta de nacimiento', upload_to=get_docs_path, null=True)
    comprobante_domicilio = models.FileField('Comprobante de domicilio', upload_to=get_docs_path, null=True)
    curp_rfc = models.FileField('CURP/RFC', upload_to=get_docs_path, null=True)
    sat = models.FileField('SAT', upload_to=get_docs_path, null=True)
    ine = models.FileField('INE', upload_to=get_docs_path, null=True)


################ Documentos academicos ################
class DocumentosAcademicos(models.Model):
    id_trabajador = models.OneToOneField(Trabajador, on_delete=models.CASCADE, unique=True)
    primaria = models.FileField('Primaria', upload_to=get_docs_path, null=True)
    secundaria = models.FileField('Secundaria', upload_to=get_docs_path, null=True)
    preparatoria = models.FileField('Preparatoria', upload_to=get_docs_path, null=True)
    licenciatura = models.FileField('Licenciatura', upload_to=get_docs_path, null=True)
    cedula_profesional = models.FileField('Cédula profesional', upload_to=get_docs_path, null=True)

class DocumentosAcademicosConstancia(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Constancia', upload_to=get_docs_path_2)

class DocumentosAcademicosDiploma(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Diploma', upload_to=get_docs_path_2)

class DocumentosAcademicosReconocimiento(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Reconocimiento', upload_to=get_docs_path_2)

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserSCATUAZ(AbstractUser):

    materno = models.CharField(
        max_length=50,
    )

    def __str__(self):
        return str(self.first_name + ' ' + self.last_name + ' ' + self.materno).strip()

apps/usuario/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, SetPasswordForm)
from .models import UserSCATUAZ


class UsuarioForm(UserCreationForm):

    first_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el nombre(s)',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Nombre(s) es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Nombre(s)"
    )

    last_name = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el apellido paterno',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Apellido Paterno es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Apellido Paterno"
    )

    materno = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el apellido materno',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'max_length': 'La longitud maxima es de 50',
        },
        label="Apellido Materno"
    )

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        max_length=50,
        required=False,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo Electrónico es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Correo Electrónico"
    )

    password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Escribe la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Contraseña"
    )

    password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repite la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita contraseña"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = UserSCATUAZ
        fields = ['first_name', 'last_name', 'materno',
                  'username', 'email', 'password1',
                  'password2', 'is_superuser']

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'Las contraseñas no coinciden',
                code='password_mismatch',
            )
        return password2


class CambiarContrasenaForm(SetPasswordForm):

    new_password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Nueva Contraseña"
    )

    new_password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita Nueva contraseña"
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user


class ModificarUsuarioForm(UserChangeForm):

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo Electrónico es obligatorio',
        },
        label="Correo Electrónico"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = UserSCATUAZ
        fields = ['username', 'email', 'is_superuser']

    def save(self, commit=True):
        user = super(ModificarUsuarioForm, self).save(commit=False)
        if commit:
            user.save()
        return user

apps/usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UsuarioForm, CambiarContrasenaForm, ModificarUsuarioForm
from .models import UserSCATUAZ

# Create your views here.


@login_required
def lista_usuario(request):
    if request.user.is_superuser:
        usuarios = UserSCATUAZ.objects.all()
        context = {
            'actual': 'usuario',
            'usuarios': usuarios,
        }
        return render(request, 'usuario/lista_usuario.html', context)
    return redirect('trabajador:lista_trabajador')


@login_required
def agregar_usuario(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = UsuarioForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('usuario:lista_usuario')
        else:
            form = UsuarioForm()
        return render(request, 'usuario/agregar_usuario.html', {'form': form})
    return redirect('trabajador:lista_trabajador')


@login_required
def eliminar_usuario(request, id):
    if request.user.is_superuser:
        if request.method == 'POST':
            usuario = UserSCATUAZ.objects.get(pk=id)
            usuario.delete()
            return redirect('usuario:lista_usuario')
        else:
            usuario = UserSCATUAZ.objects.get(pk=id)
            return render(request, 'usuario/confirm_delete_user.html',
                          {'usuario': usuario})
    return redirect('trabajador:lista_trabajador')


@login_required
def modificar_usuario(request, id):
    if request.user.is_superuser:
        usuario = UserSCATUAZ.objects.get(pk=id)
        if request.method == 'POST':
            form = ModificarUsuarioForm(request.POST, instance=usuario)
            if form.is_valid():
                form.save()
                return redirect('usuario:lista_usuario')
        else:
            form = ModificarUsuarioForm(instance=usuario)
        return render(
            request, 'usuario/modificar_usuario.html', {
                'form': form, 'usuario': usuario})
    return redirect('trabajador:lista_trabajador')


@login_required
def cambiar_contrasena(request, id):
    if request.user.is_superuser:
        usuario = UserSCATUAZ.objects.get(pk=id)
        if request.method == 'POST':
            form = CambiarContrasenaForm(usuario, data=request.POST)
            if form.is_valid():
                form.clean_new_password2()
                form.save()
                return redirect('usuario:lista_usuario')
        else:
            form = CambiarContrasenaForm(usuario)
        return render(request, 'usuario/cambiar_contrasena.html',
                      {'form': form, 'usuario': usuario})
    return redirect('trabajador:lista_trabajador')


@login_required
def ver_usuario(request, id):
    if request.user.is_superuser:
        usuario = UserSCATUAZ.objects.get(pk=id)
        context = {
            'usuario': usuario,
        }
        return render(request, 'usuario/ver_usuario.html', context)
    return redirect('trabajador:lista_trabajador')

templates/usuario/agregar_usuario.html
{% extends 'trabajador/base.html' %}

{% block contenido %}

<form method="post" class="form pt-3">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <ul class = 'form-errors list-unstyled'>
            {% for error in form.non_field_errors %}
                <li class = "text-danger"> {{error}} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-md-6">

            <div class="row mb-2">
                <div class="col">
                    <h1 class="card-title mb-0">Nuevo Usuario</h1>
                    <p class="text-info">Todos los campos con asterisco(*) son obligatorio</p>
                </div>
            </div>

            <div class="card bg-dark text-white mb-3 shadow">
                <div class="card-header mb-3">
                    <h4 class="card-title mb-0">Datos del Nuevo Usuario</h4>
                </div>
                <div class="card-body pb-0">
                    
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_nombres">
                                *{{form.first_name.label}}
                            </label>
                            {{form.first_name}}
                            {% for error in form.first_name.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                *{{form.last_name.label}}
                            </label>
                            {{form.last_name}}
                            {% for error in form.last_name.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_materno">
                                *{{form.materno.label}}
                            </label>
                            {{form.materno}}
                            {% for error in form.materno.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_username">
                                *{{form.username.label}}
                            </label>
                            {{form.username}}
                            {% for error in form.username.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_email">
                                {{form.email.label}}
                            </label>
                            {{form.email}}
                            {% for error in form.email.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_password1">
                                *{{form.password1.label}}
                            </label>
                            {{form.password1}}
                            {% for error in form.password1.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_password2">
                                *{{form.password2.label}}
                            </label>
                            {{form.password2}}
                            {% for error in form.password2.errors %}
                                <p class="text-warning text-center pb-0 mb-0">
                                    {{error}}
                                </p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="col-11">
                            <div class="form-inline justify-content-center mb-3 mt-1">
                                {{form.is_superuser}}
                                <label class="form-check-label" for="id_is_superuser">
                                    {{form.is_superuser.label}}
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex float-right mb-3 mr-3 mt-2">
                    <button type="submit" class="btn btn-primary">Agregar</button>
                    <a href="{% url 'usuario:lista_usuario' %}" class="btn btn-secondary ml-2 border">Cancelar</a>
                </div>
            </div>
        </div>
    </div>

</form>

{% endblock contenido %}

templates/usuario/lista_usuario.html
{% extends 'trabajador/base.html' %}

{% block contenido %}

<div class="row pt-5">
    <div class="col">
        <h1>Lista de Usuarios</h1>
    </div>
    <div class="col">
        <a href="{% url 'usuario:agregar_usuario' %}" class="btn btn-success bt-sm float-right">Agregar Usuario</a>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        {% if usuarios|length == 0 %}
            <h4>No hay usuarios</h4>
        {% else %}
            <table class="table table-dark shadow r-click rounded-lg">
                <thead>
                    <th class="border-top-0">Usuario</th>
                    <th class="border-top-0">Nombre(s)</th>
                    <th class="border-top-0">Apellido Paterno</th>
                    <th class="border-top-0">Apellido Materno</th>
                    <th class="border-top-0">Correo Electrónico</th>
                    <th class="text-center border-top-0">Admin</th>
                    <th class="text-center border-top-0">Opciones</th>
                </thead>
                <tbody>

                    {% for usuario in usuarios %}
                        <tr onclick="verDetalle({{usuario.id}})" class="clickable">
                            <td>{{usuario.username}}</td>
                            <td>{{usuario.first_name}}</td>
                            <td>{{usuario.last_name}}</td>
                            <td>{{usuario.materno}}</td>
                            <td>{{usuario.email}}</td>
                            <td class="text-center">
                                {% if usuario.is_superuser == 1 %}
                                    Si
                                {% else %}
                                    No
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'usuario:modificar_usuario' usuario.id %}" class="btn btn-primary btn-sm mr-4">Editar</a>
                                <a href="{% url 'usuario:eliminar_usuario' usuario.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        {% endif %}
    </div>
</div>

<script>
    function verDetalle(id){

        var url = "{% url 'usuario:ver_usuario' 3435 %}";

        document.location.href = url.replace('3435', id);
    }
</script>

{% endblock contenido %}

templates/usuario/ver_usuario.html
{% extends 'trabajador/base.html' %}
{% block contenido %}

    <div class="row justify-content-center pt-4">
        <div class="col-6">

            <div class="row">                
                <div class="col">
                    <h1 class="card-title">{{usuario.first_name}} {{usuario.last_name}}
                    {{usuario.materno}}</h1>
                </div>
            </div>

            <div class="card text-white bg-dark mb-3 shadow">
                <div class="card-header">
                    <h4 class="card-title mb-0">Datos del usuario</h4>
                </div>
                <div class="card-body pb-0">
                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_first_name">
                                Nombre(s)
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.first_name}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                Apellido Paterno
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.last_name}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_materno">
                                Apellido Materno
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.materno}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_usuario">
                                Usuario
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.username}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_correo">
                                Correo Electrónico
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{{usuario.email}}"
                            />
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-11">
                            <label for="id_paterno">
                                ¿Es administrador?
                            </label>
                            <input
                                disabled
                                type="text"
                                class="form-control"
                                value="{% if usuario.is_superuser %}Si{% else %}No{% endif %}"
                            />
                        </div>
                    </div>
                </div>
                <div class="d-flex float-right mr-3 mb-3 mt-2">
                    <a href="{% url 'usuario:modificar_usuario' usuario.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'usuario:eliminar_usuario' usuario.id %}" class="btn btn-danger ml-2">Eliminar</a>
                    <button onClick="javascript:history.go(-1);"
                        class="btn btn-secondary ml-2 border">
                        Regresar
                    </button>
                </div>
            </div>

        </div>
    </div>


{% endblock contenido %}