apps/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.iniciar_sesion, name='iniciar_sesion'),
    path('cerrar', views.cerrar_sesion, name='cerrar_sesion'),
]

apps/trabajador/urls.py
from django.urls import path
from . import views

app_name = 'trabajador'

urlpatterns = [
     path('', views.lista_trabajador, name='lista_trabajador'),
     path('<int:id>', views.ver_trabajador, name='ver_trabajador'),
     path('agregar', views.agregar_trabajador, name='agregar_trabajador'),
     path('eliminar/<int:pk>', views.eliminar_trabajador,
          name='eliminar_trabajador'),
     path('modificar/<int:id>', views.modificar_trabajador,
          name='modificar_trabajador'),
     path('<int:id>/archivero', views.ver_archivero, name='ver_archivero'),
     path('<int:id>/archivero/agregar/<str:archivo>', views.agregar_archivo, name='agregar_archivo')
] 

apps/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.lista_usuario, name='lista_usuario'),
    path('<int:id>', views.ver_usuario, name='ver_usuario'),
    path('agregar', views.agregar_usuario, name='agregar_usuario'),
    path('eliminar/<int:id>', views.eliminar_usuario, name='eliminar_usuario'),
    path('modificar/<int:id>', views.modificar_usuario, name='modificar_usuario'),
    path('cambiar/<int:id>', views.cambiar_contrasena, name='cambiar_contrasena'),
]

scatuaz/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trabajador/', include('apps.trabajador.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('', include('apps.login.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/trabajador/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from apps.usuario.models import UserSCATUAZ

OPCIONES_SEXO = (
    ('0', 'Masculino'),
    ('1', 'Femenino'),
)

OPCIONES_ESTUDIOS = (
    ('0', 'Primaria'),
    ('1', 'Secundaria'),
    ('2', 'Bachillerato o Preparatoria'),
    ('3', 'Carrera Comercial'),
    ('4', 'Carrera Técnica'),
    ('5', 'Normal'),
    ('6', 'Normal Superior'),
    ('7', 'Licenciatura'),
    ('8', 'Pasante de Carrera Profesional'),
    ('9', 'Especialidad'),
    ('10', 'Maestría'),
    ('11', 'Doctorado'),
    ('12', 'Pasante de Maestría'),
    ('13', 'Candidato a Doctor'),
    ('14', 'Postdoctorado'),
)

OPCIONES_BOOL = (
    ('0', 'No'),
    ('1', 'Si'),
)

def get_docs_path(instance, filename):
    return f'docs/trabajador/{instance.id_trabajador.rfc}/{filename}'

def get_docs_path_2(instance, filename):
    return f'docs/trabajador/{instance.id_doc_academicos.id_trabajador.rfc}/{filename}'

class Trabajador(models.Model):
    nombre = models.CharField('*Nombre(s)', max_length=100)
    paterno = models.CharField('*Primer apellido', max_length=100)
    materno = models.CharField('*Segundo apellido', max_length=100)
    rfc = models.CharField('*RFC', max_length=13, unique=True)
    curp = models.CharField('*CURP', max_length=18, unique=True)
    sexo = models.CharField('*Genero', max_length=1, choices=OPCIONES_SEXO)
    pais_residencia = models.CharField('*Pais de residencia', max_length=100)
    estado_residencia = models.CharField('*Estado de residencia', max_length=100)
    municipio_residencia = models.CharField('*Municipio de residencia', max_length=100)
    calle = models.CharField('*Calle', max_length=100)
    numero = models.CharField('*Numero', max_length=10)
    colonia = models.CharField('*Colonia', max_length=100)
    cp = models.CharField('*CP', max_length=6)
    telefono = models.CharField('*Telefono', max_length=10, unique=True)
    email = models.CharField('*Correo electronico', max_length=50, unique=True)
    matricula_administrativo = models.CharField('*Matricula administrativa', max_length=6, unique=True)
    matricula_gremial = models.CharField('*Matricula gremial', max_length=6, unique=True)
    grado_max_estudios = models.CharField('*Grado maximo de estudios', max_length=2, choices=OPCIONES_ESTUDIOS)
    nss = models.CharField('*Numero de seguro social (NSS)', max_length=11, unique=True)
    no_issste = models.CharField('*Numero de ISSSTE', max_length=50, unique=True)
    validado_renapo = models.CharField('Validado por Renapo', max_length=1, null=True, choices=OPCIONES_BOOL)
    validado_siri = models.CharField('Validado por Siri', max_length=1, null=True, choices=OPCIONES_BOOL)
    alta_usuario = models.ForeignKey(UserSCATUAZ, verbose_name="Usuario", null=True, on_delete=models.SET_NULL)
    alta_fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return (self.nombre + ' ' + self.paterno + ' ' + self.materno).strip()


class Actualizacion(models.Model):
    id_trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    usuario = models.ForeignKey(UserSCATUAZ, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    comentario = models.TextField('Comentario', max_length=500, null=True)
    

################ Documentos personales ################
class DocumentosPersonales(models.Model):
    id_trabajador = models.OneToOneField(Trabajador, on_delete=models.CASCADE, unique=True)
    acta_nacimiento = models.FileField('Acta de nacimiento', upload_to=get_docs_path, null=True)
    comprobante_domicilio = models.FileField('Comprobante de domicilio', upload_to=get_docs_path, null=True)
    curp_rfc = models.FileField('CURP/RFC', upload_to=get_docs_path, null=True)
    sat = models.FileField('SAT', upload_to=get_docs_path, null=True)
    ine = models.FileField('INE', upload_to=get_docs_path, null=True)


################ Documentos academicos ################
class DocumentosAcademicos(models.Model):
    id_trabajador = models.OneToOneField(Trabajador, on_delete=models.CASCADE, unique=True)
    primaria = models.FileField('Primaria', upload_to=get_docs_path, null=True)
    secundaria = models.FileField('Secundaria', upload_to=get_docs_path, null=True)
    preparatoria = models.FileField('Preparatoria', upload_to=get_docs_path, null=True)
    licenciatura = models.FileField('Licenciatura', upload_to=get_docs_path, null=True)
    cedula_profesional = models.FileField('Cédula profesional', upload_to=get_docs_path, null=True)

class DocumentosAcademicosConstancia(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Constancia', upload_to=get_docs_path_2)

class DocumentosAcademicosDiploma(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Diploma', upload_to=get_docs_path_2)

class DocumentosAcademicosReconocimiento(models.Model):
    id_doc_academicos = models.ForeignKey(DocumentosAcademicos, on_delete=models.CASCADE)
    nombre = models.CharField('Nombre de constancia', max_length=100)
    archivo = models.FileField('Reconocimiento', upload_to=get_docs_path_2)

apps/trabajador/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from . import models
from .forms import TrabajadorForm
from apps.usuario.models import UserSCATUAZ
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse

import os

trabajador_fields = [
    'nombre', 'paterno', 'materno', 'rfc', 'curp',
    'sexo', 'pais_residencia', 'estado_residencia',
    'municipio_residencia', 'calle', 'numero',
    'colonia', 'cp', 'telefono', 'email',
    'matricula_administrativo', 'matricula_gremial',
    'grado_max_estudios', 'nss', 'no_issste',
    'validado_renapo', 'validado_siri',
]

archivos_personales = [
    'acta_nacimiento', 'comprobante_domicilio', 'curp_rfc', 'sat', 'ine',
]

archivos_academicos = [
    'primaria', 'secundaria', 'preparatoria', 'licenciatura', 'cedula_profesional', 
]

nombre_archivos = {
    'acta_nacimiento': 'acta de nacimiento',
    'comprobante_domicilio': 'comprobante de domicilio',
    'curp_rfc': 'CURP/RFC',
    'sat': 'SAT',
    'ine': 'INE',
    'primaria': 'primaria',
    'secundaria': 'secundaria',
    'preparatoria': 'preparatoria',
    'licenciatura': 'licenciatura',
    'cedula_profesional': 'cédula profesional',
    'constancia': 'constancia',
    'diploma': 'diploma',
    'reconocimiento': 'reconocimiento'
}

def comparar_forms(form):
    campos_actualizados = ''
    for field in trabajador_fields:
        if field in form.changed_data:
            if campos_actualizados != '':
                campos_actualizados += ', '
            campos_actualizados += field
    return campos_actualizados


@login_required
def lista_trabajador(request):
    trabajadores = models.Trabajador.objects.all().order_by('id')
    query = request.GET.get('q')
    if query:
        trabajadores = models.Trabajador.objects.filter(
            Q(nombre=query) | Q(paterno=query) | Q(
                materno=query) | Q(rfc=query)
        ).distinct()

    paginator = Paginator(trabajadores, 10)
    numero_pagina = request.GET.get('page')

    try:
        pagina = paginator.page(numero_pagina)
    except PageNotAnInteger:
        pagina = paginator.page(1)
    except EmptyPage:
        pagina = paginator.page(paginator.num_pages)

    context = {
        'actual': 'trabajador',
        'pagina': pagina,
    }
    return render(request, 'trabajador/lista_trabajador.html', context)


@login_required
def ver_trabajador(request, id):
    trabajador = models.Trabajador.objects.get(pk=id)
    try:
        actualizaciones = models.Actualizacion.objects.filter(id_trabajador_id=id)
    except BaseException:
        actualizaciones = ()
    context = {
        'trabajador': trabajador,
        'actualizaciones': actualizaciones
    }

    return render(request, 'trabajador/ver_trabajador.html', context)


@login_required
def agregar_trabajador(request):
    if request.method == 'POST':
        form = TrabajadorForm(request.POST)
        if form.is_valid():
            tmp = form.save(commit=False)
            usuario = UserSCATUAZ.objects.get(pk=request.user.id)
            tmp.alta_usuario = usuario
            tmp.save()
            messages.success(request, 'El trabajador quedo guardado.')
            return redirect('trabajador:ver_trabajador', id=tmp.id)
        messages.error(request, 'Corrige los errores.')
    else:
        form = TrabajadorForm()
    context = {
        'form': form
    }
    return render(request, 'trabajador/agregar_trabajador.html', context)


@login_required
def modificar_trabajador(request, id):
    trabajador = models.Trabajador.objects.get(pk=id)
    if request.method == 'POST':
        form = TrabajadorForm(request.POST, instance=trabajador)
        if form.is_valid():
            tmp = form.save(commit=False)
            comentario = comparar_forms(form)
            models.Actualizacion.objects.create(
                id_trabajador=trabajador, usuario=request.user, comentario=comentario)
            messages.success(request, 'Los cambios quedaron guardados.')
            return redirect('trabajador:ver_trabajador', id=tmp.id)
        messages.error(request, 'Corrige los errores.')
    else:
        form = TrabajadorForm(instance=trabajador)
        context = {
            'form': form,
            'trabajador': trabajador
        }
    return render(request, 'trabajador/agregar_trabajador.html', context)


@login_required
def eliminar_trabajador(request, pk):
    if request.method == 'POST':
        try:
            trabajador = models.Trabajador.objects.get(pk=pk)
            trabajador.delete()
            messages.success(request, 'El trabajador quedo eliminado.')
            return redirect('trabajador:lista_trabajador')
        except models.Trabajador.DoesNotExist:
            trabajadores = models.Trabajador.objects.all()
            context = {
                'trabajadores': trabajadores
            }
            messages.error(request, 'El trabajador no pudo ser eliminado.')
            return render(request, 'trabajador/lista_trabajador.html', context)
    else:
        trabajador = models.Trabajador.objects.get(pk=pk)
        return render(request, 'trabajador/confirm_delete.html',
                      {'trabajador': trabajador})

@login_required
def ver_archivero(request, id):
    trabajador = models.Trabajador.objects.get(pk=id)
    context = {
        'trabajador': trabajador
    }

    doc_personales = models.DocumentosPersonales.objects.filter(id_trabajador__id=trabajador.id).first()
    if doc_personales:
        context['doc_personales'] = doc_personales

    doc_academicos = models.DocumentosAcademicos.objects.filter(id_trabajador__id=trabajador.id).first()
    if doc_academicos:
        context['doc_academicos'] = doc_academicos

        doc_aca_constancia = models.DocumentosAcademicosConstancia.objects.filter(id_doc_academicos_id=doc_academicos.id)
        if doc_aca_constancia:
            context['doc_aca_constancia'] = doc_aca_constancia

        doc_aca_diploma = models.DocumentosAcademicosDiploma.objects.filter(id_doc_academicos_id=doc_academicos.id)
        if doc_aca_diploma:
            context['doc_aca_diploma'] = doc_aca_diploma
        
        doc_aca_reconocimiento = models.DocumentosAcademicosReconocimiento.objects.filter(id_doc_academicos_id=doc_academicos.id)
        if doc_aca_reconocimiento:
            context['doc_aca_reconocimiento'] = doc_aca_reconocimiento

    return render(request, 'trabajador/ver_archivero.html', context)
    
def agregar_archivo(request, id, archivo):
    trabajador = models.Trabajador.objects.get(pk=id)
    context = {
        'trabajador': trabajador
    }
    if request.method == 'POST':
        instance = None
        if archivo in archivos_personales:
            doc_personales = models.DocumentosPersonales.objects.filter(id_trabajador_id=trabajador.id).first()
            if not doc_personales:
                instance = models.DocumentosPersonales(id_trabajador_id=trabajador.id)
                setattr(instance, archivo, request.FILES[archivo])
            else:
                instance = models.DocumentosPersonales.objects.filter(id_trabajador_id=trabajador.id).first()
                if getattr(instance, archivo) and os.path.isfile(getattr(instance, archivo).path):
                    os.remove(getattr(instance, archivo).path)
                setattr(instance, archivo, request.FILES[archivo])
        elif archivo in archivos_academicos:
            doc_academicos = models.DocumentosAcademicos.objects.filter(id_trabajador_id=trabajador.id).first()
            if not doc_academicos:
                instance = models.DocumentosAcademicos(id_trabajador_id=trabajador.id)
                setattr(instance, archivo, request.FILES[archivo])
            else:
                instance = models.DocumentosAcademicos.objects.filter(id_trabajador_id=trabajador.id).first()
                if getattr(instance, archivo) and os.path.isfile(getattr(instance, archivo).path):
                    os.remove(getattr(instance, archivo).path)
                setattr(instance, archivo, request.FILES[archivo])
        elif archivo == 'constancia':
            doc_academicos = models.DocumentosAcademicos.objects.filter(id_trabajador_id=trabajador.id).first()
            if not doc_academicos:
                doc_academicos = models.DocumentosAcademicos(id_trabajador_id=trabajador.id)
            instance = models.DocumentosAcademicosConstancia(id_doc_academicos_id=doc_academicos.id)
            setattr(instance, 'archivo', request.FILES[archivo])
            setattr(instance, 'nombre', request.POST['nombre'])
        elif archivo == 'diploma':
            doc_academicos = models.DocumentosAcademicos.objects.filter(id_trabajador_id=trabajador.id).first()
            if not doc_academicos:
                doc_academicos = models.DocumentosAcademicos(id_trabajador_id=trabajador.id)
            instance = models.DocumentosAcademicosDiploma(id_doc_academicos_id=doc_academicos.id)
            setattr(instance, 'archivo', request.FILES[archivo])
            setattr(instance, 'nombre', request.POST['nombre'])
        elif archivo == 'reconocimiento':
            doc_academicos = models.DocumentosAcademicos.objects.filter(id_trabajador_id=trabajador.id).first()
            if not doc_academicos:
                doc_academicos = models.DocumentosAcademicos(id_trabajador_id=trabajador.id)
            instance = models.DocumentosAcademicosReconocimiento(id_doc_academicos_id=doc_academicos.id)
            setattr(instance, 'archivo', request.FILES[archivo])
            setattr(instance, 'nombre', request.POST['nombre'])
        else:
            messages.error(request, 'No se selecciono un archivo.')
        if instance:
            instance.save()
            messages.success(request, 'El archivo quedo guardado.')
        else:

templates/trabajador/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/styles.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <title>
        SCATUAZ
    </title>
</head>
<body class="bg-grey">
    {% block style %}{% endblock style %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'login:iniciar_sesion' %}"><h4>SCATUAZ</h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if actual == 'trabajador' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'trabajador:lista_trabajador' %}">Trabajadores</a>
                    </li>
                    {% if user.is_superuser %}    
                    <li class="nav-item {% if actual == 'usuario' %} active {% endif %}">
                        <a class="nav-link" href="{% if actual == 'usuario' %}#{% else %}{% url 'usuario:lista_usuario' %}{% endif %}">Usuarios</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-auto">
                    <a class="nav-link" href="{% url 'login:cerrar_sesion' %}"><small>Cerrar Sesión</small></a>
                </ul>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block contenido %}
            
        {% endblock contenido %}
    </div>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script>
        function abrir_modal(url) {
            $('#popup').load(url, function() {
                $(this).modal('show');
            });
            return false;
        }

        function cerrar_modal() {
            $('#popup').modal('hide');
            return false;
        }
        $(document).ready(function(){

            {% if messages %}
                {% for message in messages %}
                    $.notify({
                        icon: '{% if message.tags == "error" %}fas fa-exclamation-triangle{% elif message.tags == "success" %}fas fa-check-circle{% endif %}',
                        message: '{{ message }}',
                        target: '_top'
                    },{
                        type: "{% if message.tags == 'error' %}danger{% elif message.tags == 'success' %}success{% endif %}",
                    });
                {% endfor %}
            {% endif %}

            {% block scripts %}
            {% endblock scripts %}
        });
    </script>
</body>
</html>

templates/trabajador/confirm_delete.html
{% extends 'trabajador/base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="card col-6 bg-dark space shadow">
        <div class="card-body">
            <div class="text-center">
                <h3 class="text-white d-inline">
                    ¿Seguro que deseas eliminar al trabajador 
                    <strong class="text-danger">{{ trabajador.nombre }} {{ trabajador.paterno }} {{ trabajador.materno }}</strong>
                    con RFC <strong class="text-danger">{{ trabajador.rfc }}</strong>?
                </h3>
            </div>
            <form method="post" class="form">
                {% csrf_token %}
                <div class="d-flex justify-content-end pt-5">
                    <input type="submit" value="Eliminar" class="btn btn-danger mr-2">
                    <button type="button"
                        onClick="javascript:history.go(-1);"
                        class="btn btn-secondary"
                    >
                        Regresar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}
    

templates/trabajador/lista_trabajador.html
{% extends 'trabajador/base.html' %}

{% block contenido %}

<div class="row pt-5">
    <div class="col">
        <h1>Lista de Trabajadores</h1>
    </div>
    <div class="col">
        <a href="{% url 'trabajador:agregar_trabajador' %}" class="btn btn-success bt-sm float-right">Agregar Trabajador</a>
    </div>
</div>
<form class="form-inline" method="GET">
    <label for="id_filtro" class="font-weight-bold">Filtro:</label>
    <input id="id_filtro" class="form-control mr-2 ml-2" type="text" placeholder="Buscar trabajador" name="q" value="{{ request.GET.q }}">
    <button class="btn btn-dark my-2 my-sm-0" type="submit">Buscar</button>
</form>
<small>Se puede buscar por nombres, apellidos o RFC</small>
<div class="row mt-3">
    <div class="col">
        {% if pagina|length == 0 %}
            <h4>No hay registros</h4>
        {% else %}
            <table class="table table-dark rounded-lg shadow r-click">
                <thead>
                    <th class="border-top-0">Paterno</th>
                    <th class="border-top-0">Materno</th>
                    <th class="border-top-0">Nombre</th>
                    <th class="border-top-0">RFC</th>
                    <th class="text-center border-top-0">Opciones</th>
                </thead>
                <tbody>

                    {% for trabajador in pagina %}
                        <tr onclick="verDetalle({{trabajador.id}})" class="clickable">
                            <td>{{trabajador.paterno}}</td>
                            <td>{{trabajador.materno}}</td>
                            <td>{{trabajador.nombre}}</td>
                            <td>{{trabajador.rfc}}</td>
                            <td class="text-center">
                                <a href="{% url 'trabajador:modificar_trabajador' trabajador.id %}" class="btn btn-primary btn-sm mr-4">Editar</a>
                                <a href="{% url 'trabajador:ver_archivero' trabajador.id %}" class="btn btn-warning btn-sm mr-4">Archivero</a>
                                <a href="{% url 'trabajador:eliminar_trabajador' trabajador.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
            <!-- Paginator -->
            {% if pagina.has_other_pages %}
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not pagina.has_previous %}disabled{% endif %}">
                    <a class="page-link"
                    {% if pagina.has_previous %}
                        href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                    {% else %}
                        tabindex="-1"
                    {% endif %}
                    >Primero</a>
                </li>
                {% if pagina.number > 1 %}    
                <li class="page-item">
                    <a class="page-link"
                    {% if pagina.has_previous %}
                        href="?page={{ pagina.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                    {% else %}
                        tabindex="-1"
                    {% endif %}
                    >{{ pagina.previous_page_number }}</a>
                </li>
                {% endif %}
                    
                <li class="page-item active">
                    <span class="page-link">
                        {{ pagina.number }}
                        <span class="sr-only">(current)</span>
                    </span>    
                </li>

                {% if pagina.has_next %}
                <li class="page-item">
                    <a class="page-link"
                    {% if pagina.has_next %}
                        href="?page={{ pagina.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                    {% else %}
                        tabindex="-1"
                    {% endif %}
                    >{{ pagina.next_page_number }}</a>
                </li>
                {% endif %}
                <li class="page-item {% if not pagina.has_next %}disabled{% endif %}">
                    <a class="page-link"
                    {% if pagina.has_next %}
                        href="?page={{ pagina.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                    {% else %}
                        tabindex="-1"
                    {% endif %}
                    >Último</a>
                </li>
            </ul>
            {% endif %}
            <!-- Paginator -->
        {% endif %}
    </div>
</div>

<script>
    function verDetalle(id){

        var url = "{% url 'trabajador:ver_trabajador' 3435 %}";

        document.location.href = url.replace('3435', id);
    }
</script>

{% endblock contenido %}

templates/trabajador/modal_agregar_archivo.html
<div class="modal-dialog" id="modalBase">
    <div class="modal-content">
        <form id="form" role="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-header">
                {% if update %}
                    <h4 class="modal-title">Actualizar {{nombre_archivo}}</h4>
                {% else %}
                    <h2 class="modal-title">Agregar {{nombre_archivo}}</h2>
                {% endif %}
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <span class="border-top my-3"></span>

            <div class="modal-body">
                <label for="id_archivo">Selecciona archivo</label>
                <input class="form-control" id="id_archivo" type="file" name="{{tipo_archivo}}" required>
                {% if incluir_nombre %}
                    <label for="id_nombre">Nombre de archivo</label>
                    <input type="text" id="id_nombre" name="nombre" class="form-control">
                {% endif %}
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="submit">Guardar<i class="icon-paperplane ml-2"></i></button>
                <button type="button" class="btn btn-secondary" onclick="return cerrar_modal()">Cancelar</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("#form").submit(function (e) {
        e.preventDefault();
        
        var dest = '{% url "trabajador:agregar_archivo" id=trabajador.id archivo=tipo_archivo %}';

        $.ajax({
            type: 'POST',
            method: 'POST',
            cache: false,
            processData: false,
            contentType: false,
            url: dest,
            data: new FormData( this ),
            success: function (response) {
                console.log(response.redirect);
                window.location.href = response.redirect;
                cerrar_modal();
            },
            error: function (response) {
                $("#modalBase").replaceWith(response.responseText);
                $("#popup").animate({ scrollTop: 0 }, 'slow');
                $("#message").html('Corrige los campos con errores');
            }
        })
    })
</script>